### ISSUE TITLE
Support for multi-arch images

### ISSUE THREAD

**Issue by barthy1** [GoogleCloudPlatform/cloud-sdk-docker#232] opened 2020-11-27 16:55 UTC
Hi all,

I wonder if you consider to build multi-arch cloud sdk images with support for more than amd64 architecture?
Cloud Build actually supports `docker buildx` to run the builds for many architectures on amd64 env using qemu emulation, see https://github.com/GoogleCloudPlatform/solutions-build-multi-architecture-images-tutorial/blob/master/terraform/cloud-build/build-docker-image-trigger.yaml
And some Dockerfiles in the repo are easily extendable to use for `docker buildx` builds.

**Comment by thatnerdjosh** [comment] 2021-01-01 11:29
Any updates on this? This would be very helpful to have, especially now that M1 MacBooks are out

**Comment by barthy1** [comment] 2021-01-11 10:21
Hi @vilasj Thank you for the asnwer. What about other architectures like `s390x` or `ppc64le`?

And also could you please point me to the code, using which build for [google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz](https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-322.0.0-linux-x86_64.tar.gz) is done? Is it publicly available?

**Comment by kbandes** [comment] 2021-02-19 16:49
Sorry, the process to generate releases is internal - the source for this is not publicly available.

**Comment by barthy1** [comment] 2021-02-19 17:42
@kbandes ok, I see. So what needs to be done to request google-cloud-sdk build for let's say `s390x` architecture?

`gcr.io/google.com/cloudsdktool/cloud-sdk` image is used in core component of [Tekton](https://tekton.dev/) project - https://github.com/tektoncd/pipeline/blob/master/config/controller.yaml#L72 and it's the only one image which is still not multi-arched.
So it would be great to close this gap.

**Comment by kbandes** [comment] 2021-02-22 21:12
I'm discussing this with the Cloud SDK team.  At present, we don't actually have access to s390x hardware on which we could test this.  Can you tell us more about the priority of this request?

**Comment by barthy1** [comment] 2021-02-23 15:40
> At present, we don't actually have access to s390x hardware on which we could test this

Linux VM on s390x hardware can be provided by LinuxOne Community Cloud.
Also there is an option to get Jenkins server on s390x hardware.
Please, let me know if Cloud SDK team is interested in, I will contact people who can help to get access.

> Can you tell us more about the priority of this request?

Tekton component releases at this moment have builds for amd64, arm64, s390x and ppc64le. The only one component which is "single-arch" is cloud-sdk image. And because this image is used to setup access to cloud storage buckets, being able to use it only on Intel (amd64) installations, is limitation for Tekton users.

**Comment by odidev** [comment] 2021-03-11 11:19
Hi,
I am trying to use ‘google/cloud-sdk’ docker image in arm64 platform. It will be helpful if the image is released for linux/arm64. Do you have a release planned for this?

**Comment by thatnerdjosh** [comment] 2021-03-11 21:02
It would be nice to have a document tracking different architectures, this could easily turn into a ticket where everyone is requesting x, y, or z architecture. Having a document to see latest status would be awesome

**Comment by cpoissonnier** [comment] 2021-03-12 15:45
> Hi,
> I am trying to use ‘google/cloud-sdk’ docker image in arm64 platform. It will be helpful if the image is released for linux/arm64. Do you have a release planned for this?

Same here with a Apple M1 processor

**Comment by vilasj** [comment] 2021-04-15 02:16
Support for arm (linux and m1) is in the works.

barthy1, sorry about the delay in responding to your comment, we are still checking internally on multiarch.

**Comment by atifali** [comment] 2021-04-30 22:12
This would indeed be very useful! And I can confirm that those Dockerfiles are easily adaptable to `docker buildx`.

**Comment by martin-g** [comment] 2021-09-01 09:01
+1 for better support for more CPU architectures!

**Comment by Lorena123456789** [comment] 2021-09-02 11:31
Hi,
I am trying to use ‘google/cloud-sdk’ docker image on **armv7 platform**. Do you have a release planned for this, too? Or is it available somewhere?

**Comment by jamesdh** [comment] 2021-11-16 05:16
FWIW, I was able to build and run the [emulators Dockerfile](https://github.com/GoogleCloudPlatform/cloud-sdk-docker/blob/master/emulators/Dockerfile) natively on Apple silicon once I removed the installation of `cloud-spanner-emulator` and `bigtable` from it. Neither of those appear to be available as arm64 packages as it fails with the following: 

>ERROR: (gcloud.components.install) The following components are unknown [bigtable, cloud-spanner-emulator]

However, after removing those two components and rebuilding as arm64, changing our Postgres image to be arm64, and switching to Java 17 that has native arm64 support, our build + test times were cut in half compared to running everything via Rosetta 2 or running via our fastest Intel machine!

So yea, official M1 support would be freaking awesome!

**Comment by gregorkistler** [comment] 2022-02-13 12:14
@vilasj Do you have any news to share? 😉

**Comment by 3zzy** [comment] 2022-02-21 07:38
Hard to believe that Google doesn't have resources to provide this "feature" even after 2 years. 🤦‍♂️

**Comment by dariodariodario** [comment] 2022-02-22 11:18
This is sorely needed to work with apple silicon machines on projects using this image in integration tests. Could you at least provide the source Dockerfile?

**Comment by willfaris** [comment] 2022-03-09 02:18
Release 376.0.0 includes arm support for the image gcr.io/google.com/cloudsdktool/google-cloud-cli:debian_component_based.  

```
:~$ docker manifest inspect gcr.io/google.com/cloudsdktool/google-cloud-cli:debian_component_based
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2208,
         "digest": "sha256:08ccd1b860c7103f2bc5cb5df76ca8b0de5ea695308673764313643a8a7b9cc0",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2415,
         "digest": "sha256:ccfe878cc8e63556c8e96d829dd7ee47746fc775a691a1f0a71d031a30d71d33",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      }
   ]
}
```

The `default` and `debian_slim` images use .deb packages and we currently do not have arm versions of these packages.  The `emulators` and `alpine` images are component manager based so we could add support for arm to them in the near future if there was demand for these.

Since the product includes some native binaries we have no plans to support s390x or ppc64le architectures at this time.

I am closing this particular issue as it seems most of the demand here is for an ARM image.

**Closed by willfaris** 2022-03-09 02:18 UTC

**Comment by dariodariodario** [comment] 2022-03-14 09:56
This does not include arm support for https://hub.docker.com/r/google/cloud-sdk not just the cli version? We have projects using that image will it be made available?
