### ISSUE TITLE
google/cloud-sdk:latest missing component `pubsub-emulator`

### ISSUE THREAD

**Issue by kpurdon** [GoogleCloudPlatform/cloud-sdk-docker#227] opened 2020-10-14 22:28 UTC
I just started receiving this error today, I would expect this component to be installed (it has been previously). Any guidance?

<img width="616" alt="Screen Shot 2020-10-14 at 4 26 45 PM" src="https://user-images.githubusercontent.com/5130441/96052145-29604880-0e3a-11eb-8f9d-1eaa012374cd.png">

**Comment by kpurdon** [comment] 2020-10-14 22:35
I see https://github.com/GoogleCloudPlatform/cloud-sdk-docker/commit/b75f3f692e7eb9d496e3cb8e46f68ec48f5a63e9. Is it expected now that this image will not support the pubsub emulator until it supports Java 11? Is there a plan for that to happen?

I'll switch to `debian_component_based` for now. Just got caught off guard by this change.

**Comment by sjudeng** [comment] 2020-10-14 23:30
There was a comment in an earlier issue that said it's expected but will hopefully be fixed in the next release. https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/225

**Comment by vilasj** [comment] 2020-10-15 00:51
Duplicate of #225

**Closed by vilasj** 2020-10-15 00:51 UTC
