### ISSUE TITLE
Cloud build gsutil step broken with tag 304.0.0

### ISSUE THREAD

**Issue by stewartbryson** [GoogleCloudPlatform/cloud-sdk-docker#216] opened 2020-08-04 23:30 UTC
A `gsutil` step in Google Cloud Build is no longer working starting with tag `304.0.0`.

From my `cloudbuild.yaml` file:

```
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: copy-sessions
  args:
    - 'gsutil'
    - 'cp'
    - 'gs://rpa-etl-converter/build-resources/sessions.json'
    - .
```

Error from the Cloud Build UI:

```
Step #0 - "copy-sessions": gcr.io/google.com/cloudsdktool/cloud-sdk:latest
Step #0 - "copy-sessions": ERROR: (gsutil) Failed to create the default configuration. Ensure your have the correct permissions on: [/builder/home/.config/gcloud/configurations].
Step #0 - "copy-sessions":   Could not create directory [/builder/home/.config/gcloud/configurations]: Permission denied.
```

Changed `cloudbuild.yaml` to this and the error disappears:

```
- name: gcr.io/google.com/cloudsdktool/cloud-sdk:303.0.0
  id: copy-sessions
  args:
    - 'gsutil'
    - 'cp'
    - 'gs://rpa-etl-converter/build-resources/sessions.json'
    - .
```

**Comment by gerbercj** [comment] 2020-08-04 23:40
This appears to be a duplicate of #214, which should have been addressed a short while ago. Could you confirm if this is still occuring?

**Comment by stewartbryson** [comment] 2020-08-04 23:44
Resolved. Thank you.

**Closed** 2020-08-04 23:44 UTC
