### ISSUE TITLE
Beta command group not installed

### ISSUE THREAD

**Issue by jasperkuperus** [GoogleCloudPlatform/cloud-sdk-docker#74] opened 2017-06-19 12:00 UTC
I see the alpine version of the Dockerfile has been published. The pre-alpine version used to have the beta components installed, can this also be the default for the alpine version?

```
$ docker run -it google/cloud-sdk:latest /bin/bash
bash-4.3# gcloud beta emulators pubsub start
You do not currently have this command group installed.  Using it 
requires the installation of components: [beta]


Your current Cloud SDK version is: 159.0.0
Installing components from version: 159.0.0

ERROR: (gcloud) Your current working directory is inside the Cloud SDK install root: /google-cloud-sdk.  In order to perform this update, run the command from outside of this directory.
```

**Comment by ahmetb** [comment] 2017-06-19 15:53
We're not planning to install additional components to the base image.

However it looks like there's multiple issues demanding such stuff to be installed. Maybe we can release a flavor that has a lot of stuff preinstalled. cc: @salrashid123

**Comment by chadbr** [comment] 2017-06-19 16:27
@ahmetb this seems to be a regression of https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/42

breaking build pipelines :/

thanks -- Chad

**Comment by ahmetb** [comment] 2017-06-19 16:38
I want to find out if you folks are okay with maintaining an extra Dockerfile:

```
FROM google/cloud-sdk:[tag]
RUN gcloud components install [...] -q
```

and running: `docker build -t my-gcloud .`, then using this image in your build-CI/CD systems? When we start installing additional components (and their dependencies) we easily got to 2 GB in the previous version of the image and got users complaining about the size, too.

The only other alternative I see is to have a `full` flavor that has all the components you (and other people) asking are pre-installed. I imagine doing so will get us to a 3-10x larger image size. I am not sure if it is any more desirable. Would you rather use a `full` image?

/cc'ing people on #75: @max-vogler @aisrael @MaxWinterstein would love to get your thoughts on extending the base image as illustrated above.

**Comment by ckeeney** [comment] 2017-06-19 17:10
I suggest using docker build args, and letting people specify which components they want.  [Here](https://github.com/abiosoft/caddy-docker) is a project that does something similar, and the [associated Dockerfile](https://github.com/abiosoft/caddy-docker/blob/master/Dockerfile)

**Comment by ahmetb** [comment] 2017-06-19 17:17
@ckeeney thanks for the pointer. Would you be okay with downloading the Dockerfile from the github repository and building it yourself locally. I am trying to understand if people just don't want to deal with Dockerfiles and would rather prefer a large image that has everything they need already installed in it.

**Comment by ckeeney** [comment] 2017-06-19 17:27
I would be fine with that.  `docker build` will do a bit of the work for you anyways.  See https://docs.docker.com/engine/reference/commandline/build/#build-with-url

So if you have build args setup, then on my CI server I could do

`docker build -t my-gcloud-image --build-arg components=app-engine-go,pubsub-emulator,cloud-datastore-emulator github.com/GoogleCloudPlatform/cloud-sdk-docker`

or something similar.

I don't actually use this project right now, so don't weight my vote too heavily.  I was just offering a solution.

**Comment by MaxWinterstein** [comment] 2017-06-19 18:28
Build args are fine and good, but I think the main question here is what type of image should be the default for dockerhub. 

On my CI I just refer to the dockerhub image. Building one from scratch every time takes to long, building one myself results in aging, and maybe outdated images. 

I think the main-image should be a fat one. Containing everything that the SDK has, or at least everything that was there before. So I don't need to hassle around with installing stuff, and every existing documentation and CI will just continue to work.
Besides the fat one there can be a :latest-minimal / :159-minimal image. This can be adjusted by the advanced user as needed.

**Comment by max-vogler** [comment] 2017-06-19 18:36
As solution for this and #75, I suggest to install all components that were previously available for the default tag (`latest`). The reason for this is to guarantee backwards compatibility (although I see there's a size trade-off). Introducing a breaking change like this without proper versioning of the Dockerfile broke all our builds.

The way I see it, this Docker image is mostly used for CI/CD tooling. In this use-case, backwards compatibility seems far more important than the image size (because the image will not be deployed to a production system anyway and many CI/CD services cache images locally).

Furthermore, there could be a tag named `minimal` or `slim` which does not contain any additional components. This one could be used by people with more special needs or storage restrictions.

**Comment by jasperkuperus** [comment] 2017-06-19 19:10
@ahmetb Dealing with docker files is not an issue at all, we actually did that as temporary fix ([nolemmings/google-cloud-sdk-beta](https://hub.docker.com/r/nolemmings/google-cloud-sdk-beta/). But I agree with the guys above, due to breaking backwards incompatibility it also broke our CI setup and that'll probably happen to more people. A `minimal` tag would be nice.

**Comment by aisrael** [comment] 2017-06-19 23:20
Our use case is pretty much the same as with @max-vogler. Using Gitlab CI, we've resorted to:

```
deploy_to_kates:
  stage: deploy
  image: google/cloud-sdk
  script:
    - gcloud components install --quiet kubectl
    - kubectl set image ...
```

I'm not keen on having to setup another Git repo and CI pipeline just to build `our/google-cloud-sdk-kubectl` just for a single CI step, and for the same reservations @MaxWinterstein has :( 

OTOH, I'll be watching how much time `gcloud components install --quiet kubectl` adds to our pipeline and if we find it disproportionate, will probably build our own "downstream" image or use one of the public ones above.

**Comment by salrashid123** [comment] 2017-06-20 02:44
@ahmetb @aisrael @jasperkuperus @max-vogler @MaxWinterstein 

Fair enough, how about we invert it as such:

1) :latest, :version (like :159.0.0)  is debian and installs all components (its...big)
2) :159.0.0-slim is alpine based and is the core sdk.  Or just leave alpine for documentation only and use 159.0.0-slim as debian-based basic. (seems like thats the preference so i'll do that in the next commit)
3) :legacy-latest is the original appengine_base based image from before (at latest)

The default build is debain and includes all components installed by apt-get
https://cloud.google.com/sdk/downloads#apt-get

I've staged the basic suggestions (not -slim debian or any updates to centos), here:
[https://github.com/salrashid123/cloud-sdk-docker](https://github.com/salrashid123/cloud-sdk-docker)

and the builds here: 
-[https://hub.docker.com/r/salrashid123/cloud-sdk-docker/builds/](https://hub.docker.com/r/salrashid123/cloud-sdk-docker/builds/)


- salrashid123/cloud-sdk-docker:159.0.0    < full debian based, latest
- salrashid123/cloud-sdk-docker:159.0.0    < full debian based, versioned

- salrashid123/cloud-sdk-docker:159.0.0-slim    < minmial alpine based currently
   (i'll change it to debian-based next push)

- salrashid123/cloud-sdk-docker:legacy-latest   < original appengine_based, latest



Note, the apt-installers for debain includes alpha, beta and even kubctl though it doesn't list it as such (i'll file a bug for that):

```

+-------------------------------------------------------------------------------------------------------------+
|                                                  Components                                                 |
+---------------+------------------------------------------------------+--------------------------+-----------+
|     Status    |                         Name                         |            ID            |    Size   |
+---------------+------------------------------------------------------+--------------------------+-----------+
| Not Installed | Cloud Bigtable Command Line Tool                     | cbt                      |   4.1 MiB |
| Not Installed | Cloud Datastore Emulator (Legacy)                    | gcd-emulator             |  38.1 MiB |
| Not Installed | Emulator Reverse Proxy                               | emulator-reverse-proxy   |  14.5 MiB |
| Not Installed | Google Container Registry's Docker credential helper | docker-credential-gcr    |   2.2 MiB |
| Not Installed | kubectl                                              | kubectl                  |  14.9 MiB |
| Installed     | App Engine Go Extensions                             | app-engine-go            |  97.0 MiB |
| Installed     | BigQuery Command Line Tool                           | bq                       |   < 1 MiB |
| Installed     | Cloud Bigtable Emulator                              | bigtable                 |   3.5 MiB |
| Installed     | Cloud Datalab Command Line Tool                      | datalab                  |   < 1 MiB |
| Installed     | Cloud Datastore Emulator                             | cloud-datastore-emulator |  15.4 MiB |
| Installed     | Cloud Pub/Sub Emulator                               | pubsub-emulator          |  21.0 MiB |
| Installed     | Cloud SDK Core Libraries                             | core                     |   6.2 MiB |
| Installed     | Cloud Storage Command Line Tool                      | gsutil                   |   2.9 MiB |
| Installed     | Default set of gcloud commands                       | gcloud                   |           |
| Installed     | gcloud Alpha Commands                                | alpha                    |   < 1 MiB |
| Installed     | gcloud Beta Commands                                 | beta                     |   < 1 MiB |
| Installed     | gcloud app Java Extensions                           | app-engine-java          | 132.2 MiB |
| Installed     | gcloud app Python Extensions                         | app-engine-python        |   6.4 MiB |
+---------------+------------------------------------------------------+--------------------------+-----------+
```


Finally, i'll install openssh-client and find out how to get  cloud bigtable client  (cbt) installed since its not available by apt-.

if this sounds good, i'll put a PR tomorrow and atleast :latest will be full-debian based (versioned ones follow as we'll setup those rules

**Comment by MaxWinterstein** [comment] 2017-06-20 08:36
Seems like a good idea.  
I am not sure if the "main" needs to be Debian, but as a friend of "never touch a running system" I think it should be as it was again. 

Thanks for listening to our needs! :)

**Comment by salrashid123** [comment] 2017-06-20 15:55
ok, pls see [PR78](https://github.com/GoogleCloudPlatform/cloud-sdk-docker/pull/78)

**Comment by salrashid123** [comment] 2017-06-21 14:00
the images now are debian based and versioned

```
REPOSITORY                           TAG                             IMAGE ID            CREATED             SIZE
google/cloud-sdk                     159.0.0                         c9cfc433ea64        6 hours ago         1.62GB
google/cloud-sdk                     159.0.0-slim                    0212c32b9ade        7 hours ago         463MB
google/cloud-sdk                     latest                          7d870e7e0638        7 hours ago         1.62GB
google/cloud-sdk                     legacy                          48ae1ea04468        7 hours ago         1.45GB
google/cloud-sdk                     slim                            35a167869559        7 hours ago         463MB
```

I'll file a separate Issue to figure out a way to 'strongly couple' the actual SDK install to a  [git version](https://github.com/GoogleCloudPlatform/cloud-sdk-docker/releases) as part of the checked in code. (eg, use  ```apt-get install google-cloud-sdk=158.0.0-0``` for the 158.0.0 git version and dockerhub buld)

**Comment by ahmetb** [comment] 2017-06-21 16:29
I am closing now since the additional components are pre-installed on the `:latest` and `:VERSION.0.0` flavors by default.

**Closed by ahmetb** 2017-06-21 16:29 UTC
