### ISSUE TITLE
277.0.0 broke Python

### ISSUE THREAD

**Issue by m-ender** [GoogleCloudPlatform/cloud-sdk-docker#193] opened 2020-01-22 08:00 UTC
It seems that 277.0.0-alpine no longer has Python on the path. My CI pipelines based on this image were failing this morning with 

    /bin/bash: line 130: python: command not found

Reverting to 276.0.0-alpine fixed the issue, so I assume this is something that broke with the update.

**Comment by akwodkiewicz** [comment] 2020-01-22 09:24
The same with _non-alpine_ 277.0.0.
I suppose python env variable is now pointing to Python 3. It broke pushing docker images using
`gcloud auth configure-docker && docker push $IMG_NAME`:

```
ERROR: gcloud failed to load: /tmp/_MEIypH2It/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /usr/lib/python3.7/lib-dynload/_ssl.cpython-37m-x86_64-linux-gnu.so)
    gcloud_main = _import_gcloud_main()
    import googlecloudsdk.gcloud_main
    from googlecloudsdk.api_lib.iamcredentials import util as iamcred_util
    from googlecloudsdk.api_lib.util import apis_internal
    from googlecloudsdk.core import properties
    from googlecloudsdk.core import config
    from oauth2client import client
    from oauth2client import transport
    import httplib2
    from httplib2.python3.httplib2 import *
    import ssl
    import _ssl             # if we can't import it, let the error propagate

This usually indicates corruption in your gcloud installation or problems with your Python interpreter.

Please verify that the following is the path to a working Python 2.7 executable:
    /usr/bin/python3

If it is not, please set the CLOUDSDK_PYTHON environment variable to point to a working Python 2.7 executable.

...(omitted)
```

**Comment by s4shyam95** [comment] 2020-01-22 20:49
I could not reproduce this. I ran `docker run -it --rm google/cloud-sdk:277.0.0 /bin/bash` and was able to run gcloud just fine.

**Comment by m-ender** [comment] 2020-01-22 22:51
Yeah, `gcloud` runs, but `python` doesn't (which used to work). That said, I can indeed not reproduce this on `277.0.0`, but only on `277.0.0-alpine`. So it seems the issue encountered by @akwodkiewicz is a different one (though possibly related).

**Comment by apstndb** [comment] 2020-01-23 06:49
Python is updated since #188 but many users of this image seems to depend Python 2.
Even some component of Google Cloud SDK does not yet support Python 3.
https://cloud.google.com/sdk/gcloud/reference/topic/startup?hl=en

**Comment by sjmach** [comment] 2020-01-23 10:10
There is a problem with PIP as well. PIP is not present in the image

**Comment by dclark** [comment] 2020-01-23 11:53
Error using google/cloud-sdk:277.0.0 and gsutil rsync between gcs and s3 buckets, no errors with google/cloud-sdk:276.0.0

gsutil -q -m rsync -r "gs://$BUCKET" "s3://$BUCKET"

```
'utf-8' codec can't decode byte 0x8b in position 1025: invalid start byte
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/daisy_chain_wrapper.py", line 213, in PerformDownload
    decryption_tuple=self.decryption_tuple)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/cloud_api_delegator.py", line 353, in GetObjectMedia
    decryption_tuple=decryption_tuple)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/gcs_json_api.py", line 1155, in GetObjectMedia
    decryption_tuple=decryption_tuple)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/gcs_json_api.py", line 1292, in _PerformDownload
    use_chunks=False)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/apitools/apitools/base/py/transfer.py", line 536, in StreamMedia
    additional_headers=additional_headers)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/apitools/apitools/base/py/transfer.py", line 415, in __GetChunk
    retries=self.num_retries)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/apitools/apitools/base/py/http_wrapper.py", line 356, in MakeRequest
    max_retry_wait, total_wait_sec))
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/utils/retry_util.py", line 84, in RetriesInDataTransferHandler
    http_wrapper.RethrowExceptionHandler(retry_args)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/apitools/apitools/base/py/http_wrapper.py", line 346, in MakeRequest
    check_response_func=check_response_func)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/apitools/apitools/base/py/http_wrapper.py", line 396, in _MakeRequestNoRetry
    redirections=redirections, connection_type=connection_type)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/gcs_json_media.py", line 546, in NewRequest
    connection_type=connection_type)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/oauth2client/oauth2client/transport.py", line 175, in new_request
    redirections, connection_type)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/oauth2client/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/httplib2/python3/httplib2/__init__.py", line 1514, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/gcs_json_media.py", line 453, in OverrideRequest
    headers)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/gcs_json_media.py", line 690, in _conn_request
    text_util.write_to_fd(self.stream, new_data)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/utils/text_util.py", line 382, in write_to_fd
    fd.write(six.ensure_text(data))
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/six/six.py", line 904, in ensure_text
    return s.decode(encoding, errors)

**Comment by s4shyam95** [comment] 2020-01-23 14:05
@dclark That seems to be a different issue. We are looking at the possibility of having python(2) in the alpine image as well. Will keep this thread updated.

**Comment by dinvlad** [comment] 2020-01-25 00:15
Perhaps off-topic, but what's the official guidance of Python community on this? Should Python executable from now on be named `python3`, or simply `python`? Because we expected the latter, our workflows broke when `python` was excluded from the images.

And are there plans to exclude `python` from other images (`slim`, `latest`) as well?

Thanks

**Comment by lucidsushi** [comment] 2020-01-29 14:22
I think python2/3 is fine but the "python" call has to properly bind to an executable, aka don't change to change all the call signatures to `python3  something` from `python something` ?

**Comment by AntonNguyen** [comment] 2020-02-14 13:32
I was able to get it working by running:

```bash
$ apt-get install openssl
$ export LD_LIBRARY_PATH="/usr/local/lib"
```

If anyone wants to give that a try

**Comment by sawyna** [comment] 2020-03-04 13:51
I tried patching the latest one by installing python2 related stuff by myself and seems to work fine.

Added the following in my docker file
```
RUN apt-get install -qqy python-dev
RUN apt-get install -qqy python-pip

ENV CLOUDSDK_PYTHON=python
```

**Comment by willfaris** [comment] 2020-12-07 19:24
Images have moved to Python 3.  Closing this issue.

**Closed by willfaris** 2020-12-07 19:24 UTC
