### ISSUE TITLE
Publish with version tag

### ISSUE THREAD

**Issue by whitecolor** [GoogleCloudPlatform/cloud-sdk-docker#52] opened 2016-12-07 01:34 UTC
Please publish next releases also with particular version tag, not just `latest`, to have ability to fixate it in config.

**Comment by jotaen** [comment] 2017-01-16 12:23
It would be nice, if you could add a release tag already for the current version.

**Comment by tswast** [comment] 2017-04-20 17:13
Thanks for the feedback. This image is going through some changes, and we'll try to incorporate this in the new build process. See: https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/58

I'm closing this issue as a duplicate of https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/38

**Closed by tswast** 2017-04-20 17:13 UTC
